packages:
  # all packages in direct subdirs of packages/
  - 'packages/*'
  - 'core/*'
  # all packages in subdirs of components/
  - 'components/**'
  # all packages in subdirs of utils/
  - 'utils/**'
  # exclude packages that are inside test directories
  - '!**/test/**'
